-- 쿼리 스니펫
CREATE TABLE IF NOT EXISTS QUERY_SNIPPET (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '쿼리 스니펫 ID',
    COMMON_CODE VARCHAR(150) NOT NULL COMMENT '쿼리 스니펫 코드',
    SNIPPET text NOT NULL COMMENT '스니펫',
    PRIMARY KEY (ID),
    UNIQUE (COMMON_CODE),
    FOREIGN KEY (COMMON_CODE) REFERENCES `query_snippet-common_code-code` (code)
) COMMENT = "쿼리 스니펫"
;